### ISSUE TITLE
Comments line

### ISSUE THREAD

**Issue by dshejwal** [HemantGaware/Core-JavaScript-#2]
Add a comment on this line. eg:  //console.log(oldList); 
https://github.com/HemantGaware/Core-JavaScript-/blob/f12362318ba908b03c25c2fc0bc5df11eac62a1c/JavaScript%20Grocery%20List%20Project/js/app.js#L14

**Comment by HemantGaware** [comment]
Added as comment

**Comment by dshejwal** [comment]
fix it
